---
title: "second_ten_city"
author: "Jiacheng"
date: "2022-12-04"
output: html_document
---
```{r}
library(dplyr)
library(knitr)
library(tidyverse)
library(tsibble)
library(lubridate)
#library(sf)
library(tmap)
library(terra)
library(ceramic)
library(tsibble)
library(tsibbledata)
library(ggHoriPlot)
library(ggstream)
library(colorspace)
library(ggalluvial)
library(scales)
```


Philadelohia
```{r}
setwd("/Users/yujiacheng/Desktop/Stat628_Module3/ANOVA_city")
Philadelohia_review = read.csv("Philadelohia_review.csv", header = TRUE)
df_Philadelohia_review = melt(Philadelohia_review)
ggplot(df_Philadelohia_review,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )

Philadelohia_stars = read.csv("Philadelohia_stars.csv", header = TRUE)
df_Philadelohia_stars = melt(Philadelohia_stars)
ggplot(df_Philadelohia_stars,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )
```

```{r}
bartlett.test(value ~ variable,data=df_Philadelohia_review)
#p value less than 0.05 means rejecting the null hypothesis: the assumption that the variances of each group are equal, does not satisfy the variance homogeneity, and does not pass the variance homogeneity bartlett test, so Welch's ANOVA is used.
#perform Welch's ANOVA
df_Philadelohia_review_aov <- oneway.test(value ~ variable,data=df_Philadelohia_review, var.equal = FALSE)
df_Philadelohia_review_aov
#p value is greater than 0.05, which means accepting the null hypothesis that the average number of reviews of the three types of restaurants in the city is equal, indicating that the popularity of the three types of restaurants in the city is almost the same, and there is no need for further detailed pairwise comparisons.
bartlett.test(value ~ variable,data=df_Philadelohia_stars)
#p value less than 0.05 means rejecting the null hypothesis: the assumption that the variances of each group are equal, does not satisfy the variance homogeneity, and does not pass the variance homogeneity bartlett test, so Welch's ANOVA is used.
#perform Welch's ANOVA
df_Philadelohia_stars_aov <- oneway.test(value ~ variable,data=df_Philadelohia_stars, var.equal = FALSE)
df_Philadelohia_stars_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the ratings of the three types of restaurants in the city are equal, indicating that the ratings of the three types of restaurants in the city are inconsistent, so further detailed pairwise comparisons are needed.
df_Philadelohia_stars_aov2<-aov(value ~ variable,data=df_Philadelohia_stars)
TukeyHSD(df_Philadelohia_stars_aov2,conf.level=.95)
The p values of #X2-X1 and X3-X1 are both small, indicating that the scores of Chinese restaurants in the city are significantly lower than those of the other two types of restaurants, while there is no significant difference in the scores of Japanese restaurants and Southeast Asian restaurants in the city
```

Park
```{r}
setwd("/Users/yujiacheng/Desktop/Stat628_Module3/ANOVA_city")
Park_review = read.csv("Park_review.csv", header = TRUE)
df_Park_review = melt(Park_review)
ggplot(df_Park_review,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )

Park_stars = read.csv("Park_stars.csv", header = TRUE)
df_Park_stars = melt(Park_stars)
ggplot(df_Park_stars,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )
```

Park
```{r}
bartlett.test(value ~ variable,data=df_Park_review)
#p value less than 0.05 means rejecting the null hypothesis: the assumption that the variances of each group are equal, does not satisfy the variance homogeneity, and does not pass the variance homogeneity bartlett test, so Welch's ANOVA is used.
#perform Welch's ANOVA
df_Park_review_aov <- oneway.test(value ~ variable,data=df_Park_review, var.equal = FALSE)
df_Park_review_aov
#p value is greater than 0.05, which means accepting the null hypothesis that the average number of reviews of the three types of restaurants in the city is equal, indicating that the popularity of the three types of restaurants in the city is almost the same, and there is no need for further detailed pairwise comparisons.
bartlett.test(value ~ variable,data=df_Park_stars)
#p value greater than 0.05 means accepting the null hypothesis: the assumption that the variances of each group are equal, the variance homogeneity is satisfied, and the variance homogeneity bartlett test is passed, so one way student ANOVA is used.
df_Park_stars_aov <- oneway.test(value ~ variable,data=df_Park_stars, var.equal = TRUE)
df_Park_stars_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the ratings of the three types of restaurants in the city are equal, indicating that the evaluation levels of the three types of restaurants in the city are inconsistent, so further detailed pairwise comparisons are needed
df_Park_stars_aov2<-aov(value ~ variable,data=df_Park_stars)
TukeyHSD(df_Park_stars_aov2,conf.level=.95)
#The p values of X2-X1 and X3-X1 are both small, indicating that the scores of Chinese restaurants in the city are significantly lower than those of the other two types of restaurants, while there is no significant difference in the scores of Japanese restaurants and Southeast Asian restaurants in the city.
```
Reno
```{r}
setwd("/Users/yujiacheng/Desktop/Stat628_Module3/ANOVA_city")
Reno_review = read.csv("Reno_review.csv", header = TRUE)
df_Reno_review = melt(Reno_review)
ggplot(df_Reno_review,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )

Reno_stars = read.csv("Reno_stars.csv", header = TRUE)
df_Reno_stars = melt(Reno_stars)
ggplot(df_Reno_stars,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )
```
Reno
```{r}
bartlett.test(value ~ variable,data=df_Reno_review)
#p value greater than 0.05 means accepting the null hypothesis: the assumption that the variances of each group are equal, the variance homogeneity is satisfied, and the variance homogeneity bartlett test is passed, so one way student ANOVA is used.
df_Reno_review_aov <- oneway.test(value ~ variable,data=df_Reno_review, var.equal = TRUE)
df_Reno_review_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the average number of reviews of the three types of restaurants in the city is equal, indicating that the popularity of the three types of restaurants in the city is inconsistent, so further detailed pairwise comparisons are needed
df_Reno_review_aov2<-aov(value ~ variable,data=df_Reno_review)
TukeyHSD(df_Reno_review_aov2,conf.level=.95)
#Only the p value of X2-X1 is <0.05, rejecting the null hypothesis of equality, indicating that the avg_review of Japanese restaurants is significantly different from that of Chinese restaurants, but there is no difference between Southeast Asia and Japan or Southeast Asia and Chinese restaurants. Indicates that China is lower and Japan is higher.
bartlett.test(value ~ variable,data=df_Reno_stars)
#p value greater than 0.05 means accepting the null hypothesis: the assumption that the variances of each group are equal, the variance homogeneity is satisfied, and the variance homogeneity bartlett test is passed, so one way student ANOVA is used.
df_Reno_stars_aov <- oneway.test(value ~ variable,data=df_Reno_stars, var.equal = TRUE)
df_Reno_stars_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the ratings of the three types of restaurants in the city are equal, indicating that the ratings of the three types of restaurants in the city are inconsistent, so further detailed pairwise comparisons are needed.
df_Reno_stars_aov2<-aov(value ~ variable,data=df_Reno_stars)
TukeyHSD(df_Reno_stars_aov2,conf.level=.95)
The p-values of #X2-X1 and X3-X1 are both small and significantly different, indicating that the scores of Chinese restaurants in the city are significantly lower than those of the other two categories of restaurants. However, the scores of Japanese restaurants and Southeast Asian restaurants in the city are slightly different, with Southeast Asia being the highest and Japan the second highest.
```
Riverview
```{r}
setwd("/Users/yujiacheng/Desktop/Stat628_Module3/ANOVA_city")
Riverview_review = read.csv("Riverview_review.csv", header = TRUE)
df_Riverview_review = melt(Riverview_review)
ggplot(df_Riverview_review,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )

Riverview_stars = read.csv("Riverview_stars.csv", header = TRUE)
df_Riverview_stars = melt(Riverview_stars)
ggplot(df_Riverview_stars,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )
```
Riverview
```{r}
bartlett.test(value ~ variable,data=df_Riverview_review)
#p value less than 0.05 means rejecting the null hypothesis: the assumption that the variances of each group are equal, does not satisfy the variance homogeneity, and does not pass the variance homogeneity bartlett test, so Welch's ANOVA is used.
#perform Welch's ANOVA
df_Riverview_review_aov <- oneway.test(value ~ variable,data=df_Riverview_review, var.equal = FALSE)
df_Riverview_review_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the average number of reviews of the three types of restaurants in the city is equal, indicating that the popularity of the three types of restaurants in the city is inconsistent, so further detailed pairwise comparisons are needed.
df_Riverview_review_aov2<-aov(value ~ variable,data=df_Riverview_review)
TukeyHSD(df_Riverview_review_aov2,conf.level=.95)
#Only the p value of X3-X1 is <0.05, rejecting the null hypothesis of equality, indicating that the avg_review of Southeast Asian restaurants is significantly different from that of Chinese restaurants, but Japanese and Chinese restaurants are slightly different, while Southeast Asian and Japanese restaurants have no difference. Indicates that China is lower and Southeast Asia is higher.
bartlett.test(value ~ variable,data=df_Riverview_stars)
#p值大于0.05表示接受原假设：各组方差相等的假设，满足方差齐性，通过方差齐性bartlett test，所以用one way  student ANOVA。
df_Riverview_stars_aov <- oneway.test(value ~ variable,data=df_Riverview_stars, var.equal = TRUE)
df_Riverview_stars_aov
#p value greater than 0.05 means accepting the null hypothesis: the assumption that the variances of each group are equal, the variance homogeneity is satisfied, and the variance homogeneity bartlett test is passed, so one way student ANOVA is used.
df_Riverview_stars_aov2<-aov(value ~ variable,data=df_Riverview_stars)
TukeyHSD(df_Riverview_stars_aov2,conf.level=.95)
#The p values of X2-X1 and X3-X1 are both small, indicating that the scores of Chinese restaurants in the city are significantly lower than those of the other two types of restaurants, while there is no significant difference in the scores of Japanese restaurants and Southeast Asian restaurants in the city.
```
Peter
```{r}
setwd("/Users/yujiacheng/Desktop/Stat628_Module3/ANOVA_city")
Peter_review = read.csv("Peter_review.csv", header = TRUE)
df_Peter_review = melt(Peter_review)
ggplot(df_Peter_review,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )

Peter_stars = read.csv("Peter_stars.csv", header = TRUE)
df_Peter_stars = melt(Peter_stars)
ggplot(df_Peter_stars,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )
```
Peter
```{r}
bartlett.test(value ~ variable,data=df_Peter_review)
#p value less than 0.05 means rejecting the null hypothesis: the assumption that the variances of each group are equal, does not satisfy the variance homogeneity, and does not pass the variance homogeneity bartlett test, so Welch's ANOVA is used.
#perform Welch's ANOVA
df_Peter_review_aov <- oneway.test(value ~ variable,data=df_Peter_review, var.equal = FALSE)
df_Peter_review_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the average number of reviews of the three types of restaurants in the city is equal, indicating that the popularity of the three types of restaurants in the city is inconsistent, so further detailed pairwise comparisons are needed.
df_Peter_review_aov2<-aov(value ~ variable,data=df_Peter_review)
TukeyHSD(df_Peter_review_aov2,conf.level=.95)
#The p-value of X2-X1<0.05, and the p-value of X3-X1<0.05, both reject the null hypothesis of equality, indicating that the avg_review of Chinese restaurants is significantly different from the other two types of restaurants, while the other two types of restaurants are Japanese restaurants and Southeast Asian restaurants. Restaurants are no different. It shows that the Chinese restaurant avg_review is the least and least popular.
bartlett.test(value ~ variable,data=df_Peter_stars)
#p value greater than 0.05 means accepting the null hypothesis: the assumption that the variances of each group are equal, the variance homogeneity is satisfied, and the variance homogeneity bartlett test is passed, so one way student ANOVA is used.
df_Peter_stars_aov <- oneway.test(value ~ variable,data=df_Peter_stars, var.equal = TRUE)
df_Peter_stars_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the ratings of the three types of restaurants in the city are equal, indicating that the ratings of the three types of restaurants in the city are inconsistent, so further detailed pairwise comparisons are needed.
df_Peter_stars_aov2<-aov(value ~ variable,data=df_Peter_stars)
TukeyHSD(df_Peter_stars_aov2,conf.level=.95)
#The p values of X2-X1 and X3-X1 are both small, indicating that the scores of Chinese restaurants in the city are significantly lower than those of the other two types of restaurants, while there is no significant difference in the scores of Japanese restaurants and Southeast Asian restaurants in the city.
```
Bar
```{r}
setwd("/Users/yujiacheng/Desktop/Stat628_Module3/ANOVA_city")
Bar_review = read.csv("Bar_review.csv", header = TRUE)
df_Bar_review = melt(Bar_review)
ggplot(df_Bar_review,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )

Bar_stars = read.csv("Bar_stars.csv", header = TRUE)
df_Bar_stars = melt(Bar_stars)
ggplot(df_Bar_stars,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )
```
Bar
```{r}
bartlett.test(value ~ variable,data=df_Bar_review)
#p value less than 0.05 means rejecting the null hypothesis: the assumption that the variances of each group are equal, does not satisfy the variance homogeneity, and does not pass the variance homogeneity bartlett test, so Welch's ANOVA is used.
#perform Welch's ANOVA
df_Bar_review_aov <- oneway.test(value ~ variable,data=df_Bar_review, var.equal = FALSE)
df_Bar_review_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the average number of reviews of the three types of restaurants in the city is equal, indicating that the popularity of the three types of restaurants in the city is inconsistent, so further detailed pairwise comparisons are needed.
df_Bar_review_aov2<-aov(value ~ variable,data=df_Bar_review)
TukeyHSD(df_Bar_review_aov2,conf.level=.95)
#Only the p value of X2-X1 is <0.05, rejecting the null hypothesis of equality, indicating that the avg_review of Japanese restaurants is significantly different from that of Chinese restaurants, but Southeast Asia and Chinese restaurants are slightly different, while Southeast Asia and Japan have no difference. Indicates that China is lower and Japan is higher
bartlett.test(value ~ variable,data=df_Bar_stars)
#p value greater than 0.05 means accepting the null hypothesis: the assumption that the variances of each group are equal, the variance homogeneity is satisfied, and the variance homogeneity bartlett test is passed, so one way student ANOVA is used.
df_Bar_stars_aov <- oneway.test(value ~ variable,data=df_Bar_stars, var.equal = TRUE)
df_Bar_stars_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the ratings of the three types of restaurants in the city are equal, indicating that the ratings of the three types of restaurants in the city are inconsistent, so further detailed pairwise comparisons are needed.
df_Bar_stars_aov2<-aov(value ~ variable,data=df_Bar_stars)
TukeyHSD(df_Bar_stars_aov2,conf.level=.95)
#Only X2-X1p values are very small, indicating that the scores of Chinese restaurants in the city are significantly lower than those of Japanese restaurants, but the scores of Southeast Asian restaurants in cities are also slightly lower than those of Japanese restaurants. Top rated Japanese restaurant.
```
Sparks
```{r}
setwd("/Users/yujiacheng/Desktop/Stat628_Module3/ANOVA_city")
Sparks_review = read.csv("Sparks_review.csv", header = TRUE)
df_Sparks_review = melt(Sparks_review)
ggplot(df_Sparks_review,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )

Sparks_stars = read.csv("Sparks_stars.csv", header = TRUE)
df_Sparks_stars = melt(Sparks_stars)
ggplot(df_Sparks_stars,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )
```
Sparks
```{r}
bartlett.test(value ~ variable,data=df_Sparks_review)
#p value less than 0.05 means rejecting the null hypothesis: the assumption that the variances of each group are equal, does not satisfy the variance homogeneity, and does not pass the variance homogeneity bartlett test, so Welch's ANOVA is used.
#perform Welch's ANOVA
df_Sparks_review_aov <- oneway.test(value ~ variable,data=df_Sparks_review, var.equal = FALSE)
df_Sparks_review_aov
#p value is greater than 0.05, which means accepting the null hypothesis that the average number of reviews of the three types of restaurants in the city is equal, indicating that the popularity of the three types of restaurants in the city is almost the same, and there is no need for further detailed pairwise comparisons. However, Japanese restaurants have more high-reviewed stores

bartlett.test(value ~ variable,data=df_Sparks_stars)
#p value greater than 0.05 means accepting the null hypothesis: the assumption that the variances of each group are equal, the variance homogeneity is satisfied, and the variance homogeneity bartlett test is passed, so one way student ANOVA is used.
df_Sparks_stars_aov <- oneway.test(value ~ variable,data=df_Sparks_stars, var.equal = TRUE)
df_Sparks_stars_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the ratings of the three types of restaurants in the city are equal, indicating that the ratings of the three types of restaurants in the city are inconsistent, so further detailed pairwise comparisons are needed
df_Sparks_stars_aov2<-aov(value ~ variable,data=df_Sparks_stars)
TukeyHSD(df_Sparks_stars_aov2,conf.level=.95)
The p values of #X2-X1 and X3-X1 are both small, indicating that the scores of Chinese restaurants in the city are significantly lower than those of the other two types of restaurants, while there is no significant difference in the scores of Japanese restaurants and Southeast Asian restaurants in the city.
```
Tampa
```{r}
setwd("/Users/yujiacheng/Desktop/Stat628_Module3/ANOVA_city")
Tampa_review = read.csv("Tampa_review.csv", header = TRUE)
df_Tampa_review = melt(Tampa_review)
ggplot(df_Tampa_review,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )

Tampa_stars = read.csv("Tampa_stars.csv", header = TRUE)
df_Tampa_stars = melt(Tampa_stars)
ggplot(df_Tampa_stars,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )
```
Tampa
```{r}
bartlett.test(value ~ variable,data=df_Tampa_review)
#p value less than 0.05 means rejecting the null hypothesis: the assumption that the variances of each group are equal, does not satisfy the variance homogeneity, and does not pass the variance homogeneity bartlett test, so Welch's ANOVA is used.
#perform Welch's ANOVA
df_Tampa_review_aov <- oneway.test(value ~ variable,data=df_Tampa_review, var.equal = FALSE)
df_Tampa_review_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the average number of reviews of the three types of restaurants in the city is equal, indicating that the popularity of the three types of restaurants in the city is inconsistent, so further detailed pairwise comparisons are needed.
df_Tampa_review_aov2<-aov(value ~ variable,data=df_Tampa_review)
TukeyHSD(df_Tampa_review_aov2,conf.level=.95)
#The p-value of X2-X1<0.05, and the p-value of X3-X1<0.05, both reject the null hypothesis of equality, indicating that the avg_review of Chinese restaurants is significantly different from the other two types of restaurants, while the other two types of restaurants are Japanese restaurants and Southeast Asian restaurants. Restaurants are no different. It shows that the Chinese restaurant avg_review is the least and least popular.。

bartlett.test(value ~ variable,data=df_Tampa_stars)
#p value less than 0.05 means rejecting the null hypothesis: the assumption that the variances of each group are equal, does not satisfy the variance homogeneity, and does not pass the variance homogeneity bartlett test, so Welch's ANOVA is used.
#perform Welch's ANOVA
df_Tampa_stars_aov <- oneway.test(value ~ variable,data=df_Tampa_stars, var.equal = FALSE)
df_Tampa_stars_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the ratings of the three types of restaurants in the city are equal, indicating that the ratings of the three types of restaurants in the city are inconsistent, so further detailed pairwise comparisons are needed.
df_Tampa_stars_aov2<-aov(value ~ variable,data=df_Tampa_stars)
TukeyHSD(df_Tampa_stars_aov2,conf.level=.95)
The p values of #X2-X1 and X3-X1 are both small, indicating that the scores of Chinese restaurants in the city are significantly lower than those of the other two types of restaurants, while there is no significant difference in the scores of Japanese restaurants and Southeast Asian restaurants in the city, but the scores of Southeast Asian restaurants are There are more stores with high ratings.
```
Tucson
```{r}
setwd("/Users/yujiacheng/Desktop/Stat628_Module3/ANOVA_city")
Tucson_review = read.csv("Tucson_review.csv", header = TRUE)
df_Tucson_review = melt(Tucson_review)
ggplot(df_Tucson_review,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )

Tucson_stars = read.csv("Tucson_stars.csv", header = TRUE)
df_Tucson_stars = melt(Tucson_stars)
ggplot(df_Tucson_stars,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )
```
Tucson
```{r}
bartlett.test(value ~ variable,data=df_Tucson_review)
#p value less than 0.05 means rejecting the null hypothesis: the assumption that the variances of each group are equal, does not satisfy the variance homogeneity, and does not pass the variance homogeneity bartlett test, so Welch's ANOVA is used.
#perform Welch's ANOVA
df_Tucson_review_aov <- oneway.test(value ~ variable,data=df_Tucson_review, var.equal = FALSE)
df_Tucson_review_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the average number of reviews of the three types of restaurants in the city is equal, indicating that the popularity of the three types of restaurants in the city is inconsistent, so further detailed pairwise comparisons are needed.
df_Tucson_review_aov2<-aov(value ~ variable,data=df_Tucson_review)
TukeyHSD(df_Tucson_review_aov2,conf.level=.95)
#The p-value of X2-X1<0.05, and the p-value of X3-X1<0.05, both reject the null hypothesis of equality, indicating that the avg_review of Chinese restaurants is significantly different from the other two types of restaurants, while the other two types of restaurants are Japanese restaurants and Southeast Asian restaurants. Restaurants are no different. It shows that the Chinese restaurant avg_review is the least and least popular. But there are more Japanese restaurants with high number of reviews.

bartlett.test(value ~ variable,data=df_Tucson_stars)
#p value less than 0.05 means rejecting the null hypothesis: the assumption that the variances of each group are equal, does not satisfy the variance homogeneity, and does not pass the variance homogeneity bartlett test, so Welch's ANOVA is used.
#perform Welch's ANOVA
df_Tucson_stars_aov <- oneway.test(value ~ variable,data=df_Tucson_stars, var.equal = FALSE)
df_Tucson_stars_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the ratings of the three types of restaurants in the city are equal, indicating that the ratings of the three types of restaurants in the city are inconsistent, so further detailed pairwise comparisons are needed.
df_Tucson_stars_aov2<-aov(value ~ variable,data=df_Tucson_stars)
TukeyHSD(df_Tucson_stars_aov2,conf.level=.95)
#The p values of X2-X1 and X3-X1 are both small, indicating that the scores of Chinese restaurants in the city are significantly lower than those of the other two types of restaurants, while there is no significant difference in the scores of Japanese restaurants and Southeast Asian restaurants in the city, but the scores of Southeast Asian restaurants are There are more stores with low ratings.
```
Wil
```{r}
setwd("/Users/yujiacheng/Desktop/Stat628_Module3/ANOVA_city")
Wil_review = read.csv("Wil_review.csv", header = TRUE)
df_Wil_review = melt(Wil_review)
ggplot(df_Wil_review,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )

Wil_stars = read.csv("Wil_stars.csv", header = TRUE)
df_Wil_stars = melt(Wil_stars)
ggplot(df_Wil_stars,aes(x=variable,y=value,fill=variable))+
  geom_boxplot(alpha = 1,              
               outlier.color = "black" 
               )+
  theme_bw()+                          
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5
                               )       
  )
```
Wil
```{r}
bartlett.test(value ~ variable,data=df_Wil_review)
#p value less than 0.05 means rejecting the null hypothesis: the assumption that the variances of each group are equal, does not satisfy the variance homogeneity, and does not pass the variance homogeneity bartlett test, so Welch's ANOVA is used.
#perform Welch's ANOVA
df_Wil_review_aov <- oneway.test(value ~ variable,data=df_Wil_review, var.equal = FALSE)
df_Wil_review_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the average number of reviews of the three types of restaurants in the city is equal, indicating that the popularity of the three types of restaurants in the city is inconsistent, so further detailed pairwise comparisons are needed.
df_Wil_review_aov2<-aov(value ~ variable,data=df_Wil_review)
TukeyHSD(df_Wil_review_aov2,conf.level=.95)
#The p-value of X2-X1<0.05, and the p-value of X3-X1<0.05, both reject the null hypothesis of equality, indicating that the avg_review of Chinese restaurants is significantly different from the other two types of restaurants, but the difference between Chinese restaurants and Southeast Asian restaurants is the largest . It shows that the Chinese restaurant avg_review is the least and least popular. But Southeast Asian restaurants have more restaurants with high reviews.

bartlett.test(value ~ variable,data=df_Wil_stars)
#p value less than 0.05 means rejecting the null hypothesis: the assumption that the variances of each group are equal, does not satisfy the variance homogeneity, and does not pass the variance homogeneity bartlett test, so Welch's ANOVA is used.
#perform Welch's ANOVA
df_Wil_stars_aov <- oneway.test(value ~ variable,data=df_Wil_stars, var.equal = FALSE)
df_Wil_stars_aov
#p value is less than 0.05, which means rejecting the null hypothesis that the ratings of the three types of restaurants in the city are equal, indicating that the evaluation levels of the three types of restaurants in the city are inconsistent, so further detailed pairwise comparisons are needed
df_Wil_stars_aov2<-aov(value ~ variable,data=df_Wil_stars)
TukeyHSD(df_Wil_stars_aov2,conf.level=.95)
#Only X3-X1p values are very small, indicating that the scores of Chinese restaurants in cities are significantly lower than those of Southeast Asian restaurants, but the scores of Japanese restaurants in cities are also slightly lower than those of Southeast Asian restaurants. There are a lot of high-rated restaurants in Southeast Asian restaurants.
```
